# Generated by Django 2.2.7 on 2021-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usertwitx_url_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwitx',
            name='tweet_id',
            field=models.CharField(default=-1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
