# Generated by Django 2.2.7 on 2021-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usertwitx_tweet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendtweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=50)),
                ('tweetf_id', models.CharField(max_length=100, unique=True)),
                ('desc2', models.TextField(max_length=500)),
                ('url_p2', models.TextField(max_length=500)),
            ],
        ),
    ]
